### ISSUE TITLE
Create manual test plan for end to end testing

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#46]
### **Description**
This task is created to make manual test plan for end to end testing of Audit log component.

### **Test cases to be covered**
Test cases to be tested should be listed here. Test cases should cover component level testing and full flow testing. Both positive and negative tests should be listed.

**Instantiation of different apps by different users to verify logs in authentication **
- [x] Login with TestID login method for SSN user who is Instantiating app and verify events are logged in Audit log 
- [x] Login with BankID login method for SSN user who is Instantiating app and verify events are logged in Audit log 
- [x] Login with Altinnpin login method for SSN user who is Instantiating app and verify events are logged in Audit log 
- [x] Verify events are logged when EC_user tries to login and instantiate app 
- [ ] Verify events are logged when user logged in via API using maskinporten token and instantiates an app  

**With feature toggle on and off **
- [x] Verify events are logged when Audit log feature toggle is on.
- [x] Events should not be logged in database when feature toggle is off.

**Verify logs for org and Changes made by different users on app after instantiation **
- [x] SSN user who has rights on another SSN make changes after Instantiating app  
- [x] Verify event logs are logged when org user instantiate app and all operations which are performed should also be logged 
- [x] Verify Org A who has delegated Altinn 3 App to user A and user A instantiate app on behalf of Org A. events should be logged in.
- [ ] User logged in with maskinporten token after got logged out saves refresh event in event log. 

**Verify logs when Org is delegating MaskinPortenScheme and resources  **
- [x] Event logs should be logged when Org A has delegated MaskinPorten scehme and resources to Org B

**Comment by anishastphen** [comment]
If I understand this correctly, we dont need to test login and check it in audit log.
Audit log should be checked for instantiation of apps accompanied with login, but we can discuss this with @acn-dgopa 

Test case -  SSN user who sends request for API delegation and events should be logged in Audit log --> this is not a valid scenario. SSN never gets panel for API delegering

**Comment by acn-Sneha** [comment]
what if user tries to instantiate app before login and credentials failed in that case events are logged or not logged?
