### ISSUE TITLE
TestID authentication method ID shows wrong ID in Auditlog

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-auth-audit-log#67]
When verifying audit log it shows wrong ID for user who is logged in with TestID login method @acn-dgopa

**Comment by acn-dgopa** [comment]
@acn-Sneha Can you test this now?

**Comment by acn-dgopa** [comment]
@acn-Sneha can you verify this and close the issue?

**Comment by acn-Sneha** [comment]
@acn-dgopa Verified this ok, so closing task.
