### ISSUE TITLE
Created date and time which shows in logs is different than the actual time in audit log

### ISSUE THREAD

**Issue by acn-Sneha** [Altinn/altinn-auth-audit-log#81]
I see time which comes in event logs is different than the actual time 

![Image](https://github.com/Altinn/altinn-auth-audit-log/assets/113685460/5f434062-ca90-4c31-ac05-f7d1d3485da4)

**Comment by acn-dgopa** [comment]
@acn-Sneha Our postgres servers are setup in UTC time. Therefore you see the difference. you can convert that to norsk time when you query.
